# Generated by Django 4.1.6 on 2023-02-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_calendar_nansu_notice_order_orderinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprilBack',
            fields=[
                ('april_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('april_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('april_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'april_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AprilFront',
            fields=[
                ('april_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('april_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('april_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'april_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AugBack',
            fields=[
                ('aug_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('aug_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('aug_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aug_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AugFront',
            fields=[
                ('aug_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('aug_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('aug_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aug_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('cover_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('cover_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cover',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecBack',
            fields=[
                ('dec_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('dec_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('dec_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dec_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecFront',
            fields=[
                ('dec_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('dec_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('dec_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dec_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FebBack',
            fields=[
                ('feb_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('feb_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('feb_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feb_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FebFront',
            fields=[
                ('feb_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('feb_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('feb_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feb_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JanBack',
            fields=[
                ('jan_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('jan_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('jan_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jan_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JanFront',
            fields=[
                ('jan_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('jan_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('jan_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jan_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JulyBack',
            fields=[
                ('july_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('july_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('july_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'july_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JulyFront',
            fields=[
                ('july_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('july_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('july_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'july_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JuneBack',
            fields=[
                ('june_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('june_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('june_picl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'june_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JuneFront',
            fields=[
                ('june_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('june_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('june_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'june_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarBack',
            fields=[
                ('mar_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('mar_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('mar_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mar_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarFront',
            fields=[
                ('mar_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('mar_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('mar_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mar_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MayBack',
            fields=[
                ('may_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('may_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('may_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'may_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MayFront',
            fields=[
                ('may_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('may_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('may_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'may_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NovBack',
            fields=[
                ('nov_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('nov_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('nov_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nov_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NovFront',
            fields=[
                ('nov_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('nov_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('nov_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nov_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OctBack',
            fields=[
                ('oct_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('oct_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('oct_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oct_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OctFront',
            fields=[
                ('oct_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('oct_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('oct_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oct_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prolog',
            fields=[
                ('prolog_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('prolog_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prolog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SepBack',
            fields=[
                ('sep_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('sep_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('sep_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sep_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SepFront',
            fields=[
                ('sep_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('sep_memo', models.CharField(blank=True, max_length=200, null=True)),
                ('sep_pic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sep_front',
                'managed': False,
            },
        ),
    ]
