# Generated by Django 4.1.6 on 2023-03-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_nansu_related_nansu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='nansu',
            name='related_nansu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='app.nansu'),
        ),
    ]
