# Generated by Django 4.1.6 on 2023-03-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_image_options_alter_nansu_related_nansu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
