# Generated by Django 4.1.6 on 2023-03-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(null=True, upload_to='%Y%m%d/'),
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
