# Generated by Django 4.1.6 on 2023-03-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_appimage_remove_image_image_file_image_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'managed': False},
        ),
    ]
