# Generated by Django 4.1.6 on 2023-03-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_image_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppImage',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
