# Generated by Django 4.1.6 on 2023-03-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_appimage_alter_image_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'managed': True},
        ),
    ]
