# Generated by Django 4.1.6 on 2023-03-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'managed': False},
        ),
    ]
