# Generated by Django 4.1.6 on 2023-03-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_imagetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
