# Generated by Django 4.1.6 on 2023-03-06 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTest',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='nansu',
        ),
        migrations.AddField(
            model_name='calendar',
            name='nansu_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='app.nansu'),
        ),
    ]
