# Generated by Django 4.1.6 on 2023-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_aprilback_april_idx_alter_aprilfront_april_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprilback',
            old_name='april_seq',
            new_name='april_nansu',
        ),
        migrations.RenameField(
            model_name='aprilfront',
            old_name='april_seq',
            new_name='april_nansu',
        ),
        migrations.RenameField(
            model_name='augback',
            old_name='aug_seq',
            new_name='aug_nansu',
        ),
        migrations.RenameField(
            model_name='augfront',
            old_name='aug_seq',
            new_name='aug_nansu',
        ),
        migrations.RenameField(
            model_name='cover',
            old_name='cover_seq',
            new_name='cover_nansu',
        ),
        migrations.RenameField(
            model_name='decback',
            old_name='dec_seq',
            new_name='dec_nansu',
        ),
        migrations.RenameField(
            model_name='decfront',
            old_name='dec_seq',
            new_name='dec_nansu',
        ),
        migrations.RenameField(
            model_name='febback',
            old_name='feb_seq',
            new_name='feb_nansu',
        ),
        migrations.RenameField(
            model_name='febfront',
            old_name='feb_seq',
            new_name='feb_nansu',
        ),
        migrations.RenameField(
            model_name='janback',
            old_name='jan_seq',
            new_name='jan_nansu',
        ),
        migrations.RenameField(
            model_name='janfront',
            old_name='jan_seq',
            new_name='jan_nansu',
        ),
        migrations.RenameField(
            model_name='julyback',
            old_name='july_seq',
            new_name='july_nansu',
        ),
        migrations.RenameField(
            model_name='julyfront',
            old_name='july_seq',
            new_name='july_nansu',
        ),
        migrations.RenameField(
            model_name='juneback',
            old_name='june_seq',
            new_name='june_nansu',
        ),
        migrations.RenameField(
            model_name='juneback',
            old_name='june_picl',
            new_name='june_pic',
        ),
        migrations.RenameField(
            model_name='junefront',
            old_name='june_seq',
            new_name='june_nansu',
        ),
        migrations.RenameField(
            model_name='marback',
            old_name='mar_seq',
            new_name='mar_nansu',
        ),
        migrations.RenameField(
            model_name='marfront',
            old_name='mar_seq',
            new_name='mar_nansu',
        ),
        migrations.RenameField(
            model_name='mayback',
            old_name='may_seq',
            new_name='may_nansu',
        ),
        migrations.RenameField(
            model_name='mayfront',
            old_name='may_seq',
            new_name='may_nansu',
        ),
        migrations.RenameField(
            model_name='novback',
            old_name='nov_seq',
            new_name='nov_nansu',
        ),
        migrations.RenameField(
            model_name='novfront',
            old_name='nov_seq',
            new_name='nov_nansu',
        ),
        migrations.RenameField(
            model_name='octback',
            old_name='oct_seq',
            new_name='oct_nansu',
        ),
        migrations.RenameField(
            model_name='octfront',
            old_name='oct_seq',
            new_name='oct_nansu',
        ),
        migrations.RenameField(
            model_name='prolog',
            old_name='prolog_seq',
            new_name='prolog_nansu',
        ),
        migrations.RenameField(
            model_name='sepback',
            old_name='sep_seq',
            new_name='sep_nansu',
        ),
        migrations.RenameField(
            model_name='sepfront',
            old_name='sep_seq',
            new_name='sep_nansu',
        ),
        migrations.AddField(
            model_name='aprilback',
            name='april_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aprilback',
            name='april_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aprilfront',
            name='april_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aprilfront',
            name='april_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='augback',
            name='aug_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='augback',
            name='aug_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='augfront',
            name='aug_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='augfront',
            name='aug_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cover',
            name='cover_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cover',
            name='cover_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='decback',
            name='dec_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='decback',
            name='dec_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='decfront',
            name='dec_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='decfront',
            name='dec_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='febback',
            name='feb_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='febback',
            name='feb_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='febfront',
            name='feb_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='febfront',
            name='feb_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='janback',
            name='jan_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='janback',
            name='jan_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='janfront',
            name='jan_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='janfront',
            name='jan_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='julyback',
            name='july_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='julyback',
            name='july_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='julyfront',
            name='july_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='julyfront',
            name='july_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='juneback',
            name='june_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='juneback',
            name='june_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='junefront',
            name='june_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='junefront',
            name='june_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='marback',
            name='mar_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='marback',
            name='mar_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='marfront',
            name='mar_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='marfront',
            name='mar_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mayback',
            name='may_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mayback',
            name='may_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mayfront',
            name='may_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mayfront',
            name='may_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nansu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='novback',
            name='nov_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='novback',
            name='nov_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='novfront',
            name='nov_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='novfront',
            name='nov_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='octback',
            name='oct_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='octback',
            name='oct_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='octfront',
            name='oct_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='octfront',
            name='oct_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='prolog',
            name='prolog_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='prolog',
            name='prolog_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sepback',
            name='sep_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sepback',
            name='sep_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sepfront',
            name='sep_pic2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sepfront',
            name='sep_pic3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='janfront',
            name='jan_idx',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
