# Generated by Django 4.1.6 on 2023-02-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=30)),
                ('admin_pw', models.CharField(max_length=30)),
                ('sub_admin_id', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_admin_pw', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(blank=True, max_length=20, null=True)),
                ('years', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nansu',
            fields=[
                ('nansu_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('nansu', models.CharField(blank=True, max_length=100, null=True)),
                ('nansu_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permission', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nansu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice', models.CharField(blank=True, max_length=200, null=True)),
                ('notice_seq', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=45)),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('order_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('zipcode', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_info_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('calendar_file', models.IntegerField(blank=True, null=True)),
                ('order_state', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'order_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
